// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v3.12.4
// source: internal/grpc_server/proto/urlshortener.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ShortenURLReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	OriginalUrl string `protobuf:"bytes,1,opt,name=original_url,json=originalUrl,proto3" json:"original_url,omitempty"`
}

func (x *ShortenURLReq) Reset() {
	*x = ShortenURLReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_grpc_server_proto_urlshortener_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ShortenURLReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShortenURLReq) ProtoMessage() {}

func (x *ShortenURLReq) ProtoReflect() protoreflect.Message {
	mi := &file_internal_grpc_server_proto_urlshortener_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShortenURLReq.ProtoReflect.Descriptor instead.
func (*ShortenURLReq) Descriptor() ([]byte, []int) {
	return file_internal_grpc_server_proto_urlshortener_proto_rawDescGZIP(), []int{0}
}

func (x *ShortenURLReq) GetOriginalUrl() string {
	if x != nil {
		return x.OriginalUrl
	}
	return ""
}

type ShortenURLRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ShortUrl string `protobuf:"bytes,1,opt,name=short_url,json=shortUrl,proto3" json:"short_url,omitempty"`
}

func (x *ShortenURLRes) Reset() {
	*x = ShortenURLRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_grpc_server_proto_urlshortener_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ShortenURLRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShortenURLRes) ProtoMessage() {}

func (x *ShortenURLRes) ProtoReflect() protoreflect.Message {
	mi := &file_internal_grpc_server_proto_urlshortener_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShortenURLRes.ProtoReflect.Descriptor instead.
func (*ShortenURLRes) Descriptor() ([]byte, []int) {
	return file_internal_grpc_server_proto_urlshortener_proto_rawDescGZIP(), []int{1}
}

func (x *ShortenURLRes) GetShortUrl() string {
	if x != nil {
		return x.ShortUrl
	}
	return ""
}

type ShortenBatchURLReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Urls []*ShortenBatchURLReq_BatchURL `protobuf:"bytes,1,rep,name=urls,proto3" json:"urls,omitempty"`
}

func (x *ShortenBatchURLReq) Reset() {
	*x = ShortenBatchURLReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_grpc_server_proto_urlshortener_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ShortenBatchURLReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShortenBatchURLReq) ProtoMessage() {}

func (x *ShortenBatchURLReq) ProtoReflect() protoreflect.Message {
	mi := &file_internal_grpc_server_proto_urlshortener_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShortenBatchURLReq.ProtoReflect.Descriptor instead.
func (*ShortenBatchURLReq) Descriptor() ([]byte, []int) {
	return file_internal_grpc_server_proto_urlshortener_proto_rawDescGZIP(), []int{2}
}

func (x *ShortenBatchURLReq) GetUrls() []*ShortenBatchURLReq_BatchURL {
	if x != nil {
		return x.Urls
	}
	return nil
}

type ShortenBatchURLRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Urls []*ShortenBatchURLRes_BatchURL `protobuf:"bytes,1,rep,name=urls,proto3" json:"urls,omitempty"`
}

func (x *ShortenBatchURLRes) Reset() {
	*x = ShortenBatchURLRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_grpc_server_proto_urlshortener_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ShortenBatchURLRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShortenBatchURLRes) ProtoMessage() {}

func (x *ShortenBatchURLRes) ProtoReflect() protoreflect.Message {
	mi := &file_internal_grpc_server_proto_urlshortener_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShortenBatchURLRes.ProtoReflect.Descriptor instead.
func (*ShortenBatchURLRes) Descriptor() ([]byte, []int) {
	return file_internal_grpc_server_proto_urlshortener_proto_rawDescGZIP(), []int{3}
}

func (x *ShortenBatchURLRes) GetUrls() []*ShortenBatchURLRes_BatchURL {
	if x != nil {
		return x.Urls
	}
	return nil
}

type GetURLReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UrlId string `protobuf:"bytes,1,opt,name=url_id,json=urlId,proto3" json:"url_id,omitempty"`
}

func (x *GetURLReq) Reset() {
	*x = GetURLReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_grpc_server_proto_urlshortener_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetURLReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetURLReq) ProtoMessage() {}

func (x *GetURLReq) ProtoReflect() protoreflect.Message {
	mi := &file_internal_grpc_server_proto_urlshortener_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetURLReq.ProtoReflect.Descriptor instead.
func (*GetURLReq) Descriptor() ([]byte, []int) {
	return file_internal_grpc_server_proto_urlshortener_proto_rawDescGZIP(), []int{4}
}

func (x *GetURLReq) GetUrlId() string {
	if x != nil {
		return x.UrlId
	}
	return ""
}

type GetURLRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	OriginalUrl string `protobuf:"bytes,1,opt,name=original_url,json=originalUrl,proto3" json:"original_url,omitempty"`
}

func (x *GetURLRes) Reset() {
	*x = GetURLRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_grpc_server_proto_urlshortener_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetURLRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetURLRes) ProtoMessage() {}

func (x *GetURLRes) ProtoReflect() protoreflect.Message {
	mi := &file_internal_grpc_server_proto_urlshortener_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetURLRes.ProtoReflect.Descriptor instead.
func (*GetURLRes) Descriptor() ([]byte, []int) {
	return file_internal_grpc_server_proto_urlshortener_proto_rawDescGZIP(), []int{5}
}

func (x *GetURLRes) GetOriginalUrl() string {
	if x != nil {
		return x.OriginalUrl
	}
	return ""
}

type GetUsersURLsReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GetUsersURLsReq) Reset() {
	*x = GetUsersURLsReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_grpc_server_proto_urlshortener_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetUsersURLsReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUsersURLsReq) ProtoMessage() {}

func (x *GetUsersURLsReq) ProtoReflect() protoreflect.Message {
	mi := &file_internal_grpc_server_proto_urlshortener_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUsersURLsReq.ProtoReflect.Descriptor instead.
func (*GetUsersURLsReq) Descriptor() ([]byte, []int) {
	return file_internal_grpc_server_proto_urlshortener_proto_rawDescGZIP(), []int{6}
}

type GetUsersURLsRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Urls []*GetUsersURLsRes_UserURL `protobuf:"bytes,1,rep,name=urls,proto3" json:"urls,omitempty"`
}

func (x *GetUsersURLsRes) Reset() {
	*x = GetUsersURLsRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_grpc_server_proto_urlshortener_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetUsersURLsRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUsersURLsRes) ProtoMessage() {}

func (x *GetUsersURLsRes) ProtoReflect() protoreflect.Message {
	mi := &file_internal_grpc_server_proto_urlshortener_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUsersURLsRes.ProtoReflect.Descriptor instead.
func (*GetUsersURLsRes) Descriptor() ([]byte, []int) {
	return file_internal_grpc_server_proto_urlshortener_proto_rawDescGZIP(), []int{7}
}

func (x *GetUsersURLsRes) GetUrls() []*GetUsersURLsRes_UserURL {
	if x != nil {
		return x.Urls
	}
	return nil
}

type DeleteUserURLsReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Urls []string `protobuf:"bytes,1,rep,name=urls,proto3" json:"urls,omitempty"`
}

func (x *DeleteUserURLsReq) Reset() {
	*x = DeleteUserURLsReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_grpc_server_proto_urlshortener_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteUserURLsReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteUserURLsReq) ProtoMessage() {}

func (x *DeleteUserURLsReq) ProtoReflect() protoreflect.Message {
	mi := &file_internal_grpc_server_proto_urlshortener_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteUserURLsReq.ProtoReflect.Descriptor instead.
func (*DeleteUserURLsReq) Descriptor() ([]byte, []int) {
	return file_internal_grpc_server_proto_urlshortener_proto_rawDescGZIP(), []int{8}
}

func (x *DeleteUserURLsReq) GetUrls() []string {
	if x != nil {
		return x.Urls
	}
	return nil
}

type DeleteUserURLsRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *DeleteUserURLsRes) Reset() {
	*x = DeleteUserURLsRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_grpc_server_proto_urlshortener_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteUserURLsRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteUserURLsRes) ProtoMessage() {}

func (x *DeleteUserURLsRes) ProtoReflect() protoreflect.Message {
	mi := &file_internal_grpc_server_proto_urlshortener_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteUserURLsRes.ProtoReflect.Descriptor instead.
func (*DeleteUserURLsRes) Descriptor() ([]byte, []int) {
	return file_internal_grpc_server_proto_urlshortener_proto_rawDescGZIP(), []int{9}
}

type GetStatsReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GetStatsReq) Reset() {
	*x = GetStatsReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_grpc_server_proto_urlshortener_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetStatsReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStatsReq) ProtoMessage() {}

func (x *GetStatsReq) ProtoReflect() protoreflect.Message {
	mi := &file_internal_grpc_server_proto_urlshortener_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStatsReq.ProtoReflect.Descriptor instead.
func (*GetStatsReq) Descriptor() ([]byte, []int) {
	return file_internal_grpc_server_proto_urlshortener_proto_rawDescGZIP(), []int{10}
}

type GetStatsRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Urls  int32 `protobuf:"varint,1,opt,name=urls,proto3" json:"urls,omitempty"`
	Users int32 `protobuf:"varint,2,opt,name=users,proto3" json:"users,omitempty"`
}

func (x *GetStatsRes) Reset() {
	*x = GetStatsRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_grpc_server_proto_urlshortener_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetStatsRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStatsRes) ProtoMessage() {}

func (x *GetStatsRes) ProtoReflect() protoreflect.Message {
	mi := &file_internal_grpc_server_proto_urlshortener_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStatsRes.ProtoReflect.Descriptor instead.
func (*GetStatsRes) Descriptor() ([]byte, []int) {
	return file_internal_grpc_server_proto_urlshortener_proto_rawDescGZIP(), []int{11}
}

func (x *GetStatsRes) GetUrls() int32 {
	if x != nil {
		return x.Urls
	}
	return 0
}

func (x *GetStatsRes) GetUsers() int32 {
	if x != nil {
		return x.Users
	}
	return 0
}

type PingReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *PingReq) Reset() {
	*x = PingReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_grpc_server_proto_urlshortener_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PingReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingReq) ProtoMessage() {}

func (x *PingReq) ProtoReflect() protoreflect.Message {
	mi := &file_internal_grpc_server_proto_urlshortener_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingReq.ProtoReflect.Descriptor instead.
func (*PingReq) Descriptor() ([]byte, []int) {
	return file_internal_grpc_server_proto_urlshortener_proto_rawDescGZIP(), []int{12}
}

type PingRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *PingRes) Reset() {
	*x = PingRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_grpc_server_proto_urlshortener_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PingRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingRes) ProtoMessage() {}

func (x *PingRes) ProtoReflect() protoreflect.Message {
	mi := &file_internal_grpc_server_proto_urlshortener_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingRes.ProtoReflect.Descriptor instead.
func (*PingRes) Descriptor() ([]byte, []int) {
	return file_internal_grpc_server_proto_urlshortener_proto_rawDescGZIP(), []int{13}
}

type ShortenBatchURLReq_BatchURL struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CorrelationId string `protobuf:"bytes,1,opt,name=correlation_id,json=correlationId,proto3" json:"correlation_id,omitempty"`
	OriginalUrl   string `protobuf:"bytes,2,opt,name=original_url,json=originalUrl,proto3" json:"original_url,omitempty"`
}

func (x *ShortenBatchURLReq_BatchURL) Reset() {
	*x = ShortenBatchURLReq_BatchURL{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_grpc_server_proto_urlshortener_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ShortenBatchURLReq_BatchURL) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShortenBatchURLReq_BatchURL) ProtoMessage() {}

func (x *ShortenBatchURLReq_BatchURL) ProtoReflect() protoreflect.Message {
	mi := &file_internal_grpc_server_proto_urlshortener_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShortenBatchURLReq_BatchURL.ProtoReflect.Descriptor instead.
func (*ShortenBatchURLReq_BatchURL) Descriptor() ([]byte, []int) {
	return file_internal_grpc_server_proto_urlshortener_proto_rawDescGZIP(), []int{2, 0}
}

func (x *ShortenBatchURLReq_BatchURL) GetCorrelationId() string {
	if x != nil {
		return x.CorrelationId
	}
	return ""
}

func (x *ShortenBatchURLReq_BatchURL) GetOriginalUrl() string {
	if x != nil {
		return x.OriginalUrl
	}
	return ""
}

type ShortenBatchURLRes_BatchURL struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CorrelationId string `protobuf:"bytes,1,opt,name=correlation_id,json=correlationId,proto3" json:"correlation_id,omitempty"`
	ShortUrl      string `protobuf:"bytes,2,opt,name=short_url,json=shortUrl,proto3" json:"short_url,omitempty"`
}

func (x *ShortenBatchURLRes_BatchURL) Reset() {
	*x = ShortenBatchURLRes_BatchURL{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_grpc_server_proto_urlshortener_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ShortenBatchURLRes_BatchURL) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShortenBatchURLRes_BatchURL) ProtoMessage() {}

func (x *ShortenBatchURLRes_BatchURL) ProtoReflect() protoreflect.Message {
	mi := &file_internal_grpc_server_proto_urlshortener_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShortenBatchURLRes_BatchURL.ProtoReflect.Descriptor instead.
func (*ShortenBatchURLRes_BatchURL) Descriptor() ([]byte, []int) {
	return file_internal_grpc_server_proto_urlshortener_proto_rawDescGZIP(), []int{3, 0}
}

func (x *ShortenBatchURLRes_BatchURL) GetCorrelationId() string {
	if x != nil {
		return x.CorrelationId
	}
	return ""
}

func (x *ShortenBatchURLRes_BatchURL) GetShortUrl() string {
	if x != nil {
		return x.ShortUrl
	}
	return ""
}

type GetUsersURLsRes_UserURL struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	OriginalUrl string `protobuf:"bytes,1,opt,name=original_url,json=originalUrl,proto3" json:"original_url,omitempty"`
	ShortUrl    string `protobuf:"bytes,2,opt,name=short_url,json=shortUrl,proto3" json:"short_url,omitempty"`
}

func (x *GetUsersURLsRes_UserURL) Reset() {
	*x = GetUsersURLsRes_UserURL{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_grpc_server_proto_urlshortener_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetUsersURLsRes_UserURL) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUsersURLsRes_UserURL) ProtoMessage() {}

func (x *GetUsersURLsRes_UserURL) ProtoReflect() protoreflect.Message {
	mi := &file_internal_grpc_server_proto_urlshortener_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUsersURLsRes_UserURL.ProtoReflect.Descriptor instead.
func (*GetUsersURLsRes_UserURL) Descriptor() ([]byte, []int) {
	return file_internal_grpc_server_proto_urlshortener_proto_rawDescGZIP(), []int{7, 0}
}

func (x *GetUsersURLsRes_UserURL) GetOriginalUrl() string {
	if x != nil {
		return x.OriginalUrl
	}
	return ""
}

func (x *GetUsersURLsRes_UserURL) GetShortUrl() string {
	if x != nil {
		return x.ShortUrl
	}
	return ""
}

var File_internal_grpc_server_proto_urlshortener_proto protoreflect.FileDescriptor

var file_internal_grpc_server_proto_urlshortener_proto_rawDesc = []byte{
	0x0a, 0x2d, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2f, 0x67, 0x72, 0x70, 0x63, 0x5f,
	0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x75, 0x72, 0x6c,
	0x73, 0x68, 0x6f, 0x72, 0x74, 0x65, 0x6e, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x0c, 0x75, 0x72, 0x6c, 0x73, 0x68, 0x6f, 0x72, 0x74, 0x65, 0x6e, 0x65, 0x72, 0x22, 0x32, 0x0a,
	0x0d, 0x53, 0x68, 0x6f, 0x72, 0x74, 0x65, 0x6e, 0x55, 0x52, 0x4c, 0x52, 0x65, 0x71, 0x12, 0x21,
	0x0a, 0x0c, 0x6f, 0x72, 0x69, 0x67, 0x69, 0x6e, 0x61, 0x6c, 0x5f, 0x75, 0x72, 0x6c, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x6f, 0x72, 0x69, 0x67, 0x69, 0x6e, 0x61, 0x6c, 0x55, 0x72,
	0x6c, 0x22, 0x2c, 0x0a, 0x0d, 0x53, 0x68, 0x6f, 0x72, 0x74, 0x65, 0x6e, 0x55, 0x52, 0x4c, 0x52,
	0x65, 0x73, 0x12, 0x1b, 0x0a, 0x09, 0x73, 0x68, 0x6f, 0x72, 0x74, 0x5f, 0x75, 0x72, 0x6c, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x73, 0x68, 0x6f, 0x72, 0x74, 0x55, 0x72, 0x6c, 0x22,
	0xa9, 0x01, 0x0a, 0x12, 0x53, 0x68, 0x6f, 0x72, 0x74, 0x65, 0x6e, 0x42, 0x61, 0x74, 0x63, 0x68,
	0x55, 0x52, 0x4c, 0x52, 0x65, 0x71, 0x12, 0x3d, 0x0a, 0x04, 0x75, 0x72, 0x6c, 0x73, 0x18, 0x01,
	0x20, 0x03, 0x28, 0x0b, 0x32, 0x29, 0x2e, 0x75, 0x72, 0x6c, 0x73, 0x68, 0x6f, 0x72, 0x74, 0x65,
	0x6e, 0x65, 0x72, 0x2e, 0x53, 0x68, 0x6f, 0x72, 0x74, 0x65, 0x6e, 0x42, 0x61, 0x74, 0x63, 0x68,
	0x55, 0x52, 0x4c, 0x52, 0x65, 0x71, 0x2e, 0x42, 0x61, 0x74, 0x63, 0x68, 0x55, 0x52, 0x4c, 0x52,
	0x04, 0x75, 0x72, 0x6c, 0x73, 0x1a, 0x54, 0x0a, 0x08, 0x42, 0x61, 0x74, 0x63, 0x68, 0x55, 0x52,
	0x4c, 0x12, 0x25, 0x0a, 0x0e, 0x63, 0x6f, 0x72, 0x72, 0x65, 0x6c, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d, 0x63, 0x6f, 0x72, 0x72, 0x65,
	0x6c, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x64, 0x12, 0x21, 0x0a, 0x0c, 0x6f, 0x72, 0x69, 0x67,
	0x69, 0x6e, 0x61, 0x6c, 0x5f, 0x75, 0x72, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b,
	0x6f, 0x72, 0x69, 0x67, 0x69, 0x6e, 0x61, 0x6c, 0x55, 0x72, 0x6c, 0x22, 0xa3, 0x01, 0x0a, 0x12,
	0x53, 0x68, 0x6f, 0x72, 0x74, 0x65, 0x6e, 0x42, 0x61, 0x74, 0x63, 0x68, 0x55, 0x52, 0x4c, 0x52,
	0x65, 0x73, 0x12, 0x3d, 0x0a, 0x04, 0x75, 0x72, 0x6c, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b,
	0x32, 0x29, 0x2e, 0x75, 0x72, 0x6c, 0x73, 0x68, 0x6f, 0x72, 0x74, 0x65, 0x6e, 0x65, 0x72, 0x2e,
	0x53, 0x68, 0x6f, 0x72, 0x74, 0x65, 0x6e, 0x42, 0x61, 0x74, 0x63, 0x68, 0x55, 0x52, 0x4c, 0x52,
	0x65, 0x73, 0x2e, 0x42, 0x61, 0x74, 0x63, 0x68, 0x55, 0x52, 0x4c, 0x52, 0x04, 0x75, 0x72, 0x6c,
	0x73, 0x1a, 0x4e, 0x0a, 0x08, 0x42, 0x61, 0x74, 0x63, 0x68, 0x55, 0x52, 0x4c, 0x12, 0x25, 0x0a,
	0x0e, 0x63, 0x6f, 0x72, 0x72, 0x65, 0x6c, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d, 0x63, 0x6f, 0x72, 0x72, 0x65, 0x6c, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x49, 0x64, 0x12, 0x1b, 0x0a, 0x09, 0x73, 0x68, 0x6f, 0x72, 0x74, 0x5f, 0x75, 0x72,
	0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x73, 0x68, 0x6f, 0x72, 0x74, 0x55, 0x72,
	0x6c, 0x22, 0x22, 0x0a, 0x09, 0x47, 0x65, 0x74, 0x55, 0x52, 0x4c, 0x52, 0x65, 0x71, 0x12, 0x15,
	0x0a, 0x06, 0x75, 0x72, 0x6c, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05,
	0x75, 0x72, 0x6c, 0x49, 0x64, 0x22, 0x2e, 0x0a, 0x09, 0x47, 0x65, 0x74, 0x55, 0x52, 0x4c, 0x52,
	0x65, 0x73, 0x12, 0x21, 0x0a, 0x0c, 0x6f, 0x72, 0x69, 0x67, 0x69, 0x6e, 0x61, 0x6c, 0x5f, 0x75,
	0x72, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x6f, 0x72, 0x69, 0x67, 0x69, 0x6e,
	0x61, 0x6c, 0x55, 0x72, 0x6c, 0x22, 0x11, 0x0a, 0x0f, 0x47, 0x65, 0x74, 0x55, 0x73, 0x65, 0x72,
	0x73, 0x55, 0x52, 0x4c, 0x73, 0x52, 0x65, 0x71, 0x22, 0x97, 0x01, 0x0a, 0x0f, 0x47, 0x65, 0x74,
	0x55, 0x73, 0x65, 0x72, 0x73, 0x55, 0x52, 0x4c, 0x73, 0x52, 0x65, 0x73, 0x12, 0x39, 0x0a, 0x04,
	0x75, 0x72, 0x6c, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x25, 0x2e, 0x75, 0x72, 0x6c,
	0x73, 0x68, 0x6f, 0x72, 0x74, 0x65, 0x6e, 0x65, 0x72, 0x2e, 0x47, 0x65, 0x74, 0x55, 0x73, 0x65,
	0x72, 0x73, 0x55, 0x52, 0x4c, 0x73, 0x52, 0x65, 0x73, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x55, 0x52,
	0x4c, 0x52, 0x04, 0x75, 0x72, 0x6c, 0x73, 0x1a, 0x49, 0x0a, 0x07, 0x55, 0x73, 0x65, 0x72, 0x55,
	0x52, 0x4c, 0x12, 0x21, 0x0a, 0x0c, 0x6f, 0x72, 0x69, 0x67, 0x69, 0x6e, 0x61, 0x6c, 0x5f, 0x75,
	0x72, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x6f, 0x72, 0x69, 0x67, 0x69, 0x6e,
	0x61, 0x6c, 0x55, 0x72, 0x6c, 0x12, 0x1b, 0x0a, 0x09, 0x73, 0x68, 0x6f, 0x72, 0x74, 0x5f, 0x75,
	0x72, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x73, 0x68, 0x6f, 0x72, 0x74, 0x55,
	0x72, 0x6c, 0x22, 0x27, 0x0a, 0x11, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x55, 0x73, 0x65, 0x72,
	0x55, 0x52, 0x4c, 0x73, 0x52, 0x65, 0x71, 0x12, 0x12, 0x0a, 0x04, 0x75, 0x72, 0x6c, 0x73, 0x18,
	0x01, 0x20, 0x03, 0x28, 0x09, 0x52, 0x04, 0x75, 0x72, 0x6c, 0x73, 0x22, 0x13, 0x0a, 0x11, 0x44,
	0x65, 0x6c, 0x65, 0x74, 0x65, 0x55, 0x73, 0x65, 0x72, 0x55, 0x52, 0x4c, 0x73, 0x52, 0x65, 0x73,
	0x22, 0x0d, 0x0a, 0x0b, 0x47, 0x65, 0x74, 0x53, 0x74, 0x61, 0x74, 0x73, 0x52, 0x65, 0x71, 0x22,
	0x37, 0x0a, 0x0b, 0x47, 0x65, 0x74, 0x53, 0x74, 0x61, 0x74, 0x73, 0x52, 0x65, 0x73, 0x12, 0x12,
	0x0a, 0x04, 0x75, 0x72, 0x6c, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x75, 0x72,
	0x6c, 0x73, 0x12, 0x14, 0x0a, 0x05, 0x75, 0x73, 0x65, 0x72, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x05, 0x75, 0x73, 0x65, 0x72, 0x73, 0x22, 0x09, 0x0a, 0x07, 0x50, 0x69, 0x6e, 0x67,
	0x52, 0x65, 0x71, 0x22, 0x09, 0x0a, 0x07, 0x50, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x73, 0x32, 0x82,
	0x04, 0x0a, 0x0c, 0x55, 0x52, 0x4c, 0x53, 0x68, 0x6f, 0x72, 0x74, 0x65, 0x6e, 0x65, 0x72, 0x12,
	0x46, 0x0a, 0x0a, 0x53, 0x68, 0x6f, 0x72, 0x74, 0x65, 0x6e, 0x55, 0x52, 0x4c, 0x12, 0x1b, 0x2e,
	0x75, 0x72, 0x6c, 0x73, 0x68, 0x6f, 0x72, 0x74, 0x65, 0x6e, 0x65, 0x72, 0x2e, 0x53, 0x68, 0x6f,
	0x72, 0x74, 0x65, 0x6e, 0x55, 0x52, 0x4c, 0x52, 0x65, 0x71, 0x1a, 0x1b, 0x2e, 0x75, 0x72, 0x6c,
	0x73, 0x68, 0x6f, 0x72, 0x74, 0x65, 0x6e, 0x65, 0x72, 0x2e, 0x53, 0x68, 0x6f, 0x72, 0x74, 0x65,
	0x6e, 0x55, 0x52, 0x4c, 0x52, 0x65, 0x73, 0x12, 0x55, 0x0a, 0x0f, 0x53, 0x68, 0x6f, 0x72, 0x74,
	0x65, 0x6e, 0x42, 0x61, 0x74, 0x63, 0x68, 0x55, 0x52, 0x4c, 0x12, 0x20, 0x2e, 0x75, 0x72, 0x6c,
	0x73, 0x68, 0x6f, 0x72, 0x74, 0x65, 0x6e, 0x65, 0x72, 0x2e, 0x53, 0x68, 0x6f, 0x72, 0x74, 0x65,
	0x6e, 0x42, 0x61, 0x74, 0x63, 0x68, 0x55, 0x52, 0x4c, 0x52, 0x65, 0x71, 0x1a, 0x20, 0x2e, 0x75,
	0x72, 0x6c, 0x73, 0x68, 0x6f, 0x72, 0x74, 0x65, 0x6e, 0x65, 0x72, 0x2e, 0x53, 0x68, 0x6f, 0x72,
	0x74, 0x65, 0x6e, 0x42, 0x61, 0x74, 0x63, 0x68, 0x55, 0x52, 0x4c, 0x52, 0x65, 0x73, 0x12, 0x3a,
	0x0a, 0x06, 0x47, 0x65, 0x74, 0x55, 0x52, 0x4c, 0x12, 0x17, 0x2e, 0x75, 0x72, 0x6c, 0x73, 0x68,
	0x6f, 0x72, 0x74, 0x65, 0x6e, 0x65, 0x72, 0x2e, 0x47, 0x65, 0x74, 0x55, 0x52, 0x4c, 0x52, 0x65,
	0x71, 0x1a, 0x17, 0x2e, 0x75, 0x72, 0x6c, 0x73, 0x68, 0x6f, 0x72, 0x74, 0x65, 0x6e, 0x65, 0x72,
	0x2e, 0x47, 0x65, 0x74, 0x55, 0x52, 0x4c, 0x52, 0x65, 0x73, 0x12, 0x4b, 0x0a, 0x0b, 0x47, 0x65,
	0x74, 0x55, 0x73, 0x65, 0x72, 0x55, 0x52, 0x4c, 0x73, 0x12, 0x1d, 0x2e, 0x75, 0x72, 0x6c, 0x73,
	0x68, 0x6f, 0x72, 0x74, 0x65, 0x6e, 0x65, 0x72, 0x2e, 0x47, 0x65, 0x74, 0x55, 0x73, 0x65, 0x72,
	0x73, 0x55, 0x52, 0x4c, 0x73, 0x52, 0x65, 0x71, 0x1a, 0x1d, 0x2e, 0x75, 0x72, 0x6c, 0x73, 0x68,
	0x6f, 0x72, 0x74, 0x65, 0x6e, 0x65, 0x72, 0x2e, 0x47, 0x65, 0x74, 0x55, 0x73, 0x65, 0x72, 0x73,
	0x55, 0x52, 0x4c, 0x73, 0x52, 0x65, 0x73, 0x12, 0x52, 0x0a, 0x0e, 0x44, 0x65, 0x6c, 0x65, 0x74,
	0x65, 0x55, 0x73, 0x65, 0x72, 0x55, 0x52, 0x4c, 0x73, 0x12, 0x1f, 0x2e, 0x75, 0x72, 0x6c, 0x73,
	0x68, 0x6f, 0x72, 0x74, 0x65, 0x6e, 0x65, 0x72, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x55,
	0x73, 0x65, 0x72, 0x55, 0x52, 0x4c, 0x73, 0x52, 0x65, 0x71, 0x1a, 0x1f, 0x2e, 0x75, 0x72, 0x6c,
	0x73, 0x68, 0x6f, 0x72, 0x74, 0x65, 0x6e, 0x65, 0x72, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65,
	0x55, 0x73, 0x65, 0x72, 0x55, 0x52, 0x4c, 0x73, 0x52, 0x65, 0x73, 0x12, 0x40, 0x0a, 0x08, 0x47,
	0x65, 0x74, 0x53, 0x74, 0x61, 0x74, 0x73, 0x12, 0x19, 0x2e, 0x75, 0x72, 0x6c, 0x73, 0x68, 0x6f,
	0x72, 0x74, 0x65, 0x6e, 0x65, 0x72, 0x2e, 0x47, 0x65, 0x74, 0x53, 0x74, 0x61, 0x74, 0x73, 0x52,
	0x65, 0x71, 0x1a, 0x19, 0x2e, 0x75, 0x72, 0x6c, 0x73, 0x68, 0x6f, 0x72, 0x74, 0x65, 0x6e, 0x65,
	0x72, 0x2e, 0x47, 0x65, 0x74, 0x53, 0x74, 0x61, 0x74, 0x73, 0x52, 0x65, 0x73, 0x12, 0x34, 0x0a,
	0x04, 0x50, 0x69, 0x6e, 0x67, 0x12, 0x15, 0x2e, 0x75, 0x72, 0x6c, 0x73, 0x68, 0x6f, 0x72, 0x74,
	0x65, 0x6e, 0x65, 0x72, 0x2e, 0x50, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x71, 0x1a, 0x15, 0x2e, 0x75,
	0x72, 0x6c, 0x73, 0x68, 0x6f, 0x72, 0x74, 0x65, 0x6e, 0x65, 0x72, 0x2e, 0x50, 0x69, 0x6e, 0x67,
	0x52, 0x65, 0x73, 0x42, 0x36, 0x5a, 0x34, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f,
	0x6d, 0x2f, 0x70, 0x69, 0x6e, 0x62, 0x72, 0x61, 0x69, 0x6e, 0x2f, 0x75, 0x72, 0x6c, 0x73, 0x68,
	0x6f, 0x72, 0x74, 0x65, 0x6e, 0x65, 0x72, 0x2f, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c,
	0x2f, 0x67, 0x72, 0x70, 0x63, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
}

var (
	file_internal_grpc_server_proto_urlshortener_proto_rawDescOnce sync.Once
	file_internal_grpc_server_proto_urlshortener_proto_rawDescData = file_internal_grpc_server_proto_urlshortener_proto_rawDesc
)

func file_internal_grpc_server_proto_urlshortener_proto_rawDescGZIP() []byte {
	file_internal_grpc_server_proto_urlshortener_proto_rawDescOnce.Do(func() {
		file_internal_grpc_server_proto_urlshortener_proto_rawDescData = protoimpl.X.CompressGZIP(file_internal_grpc_server_proto_urlshortener_proto_rawDescData)
	})
	return file_internal_grpc_server_proto_urlshortener_proto_rawDescData
}

var file_internal_grpc_server_proto_urlshortener_proto_msgTypes = make([]protoimpl.MessageInfo, 17)
var file_internal_grpc_server_proto_urlshortener_proto_goTypes = []any{
	(*ShortenURLReq)(nil),               // 0: urlshortener.ShortenURLReq
	(*ShortenURLRes)(nil),               // 1: urlshortener.ShortenURLRes
	(*ShortenBatchURLReq)(nil),          // 2: urlshortener.ShortenBatchURLReq
	(*ShortenBatchURLRes)(nil),          // 3: urlshortener.ShortenBatchURLRes
	(*GetURLReq)(nil),                   // 4: urlshortener.GetURLReq
	(*GetURLRes)(nil),                   // 5: urlshortener.GetURLRes
	(*GetUsersURLsReq)(nil),             // 6: urlshortener.GetUsersURLsReq
	(*GetUsersURLsRes)(nil),             // 7: urlshortener.GetUsersURLsRes
	(*DeleteUserURLsReq)(nil),           // 8: urlshortener.DeleteUserURLsReq
	(*DeleteUserURLsRes)(nil),           // 9: urlshortener.DeleteUserURLsRes
	(*GetStatsReq)(nil),                 // 10: urlshortener.GetStatsReq
	(*GetStatsRes)(nil),                 // 11: urlshortener.GetStatsRes
	(*PingReq)(nil),                     // 12: urlshortener.PingReq
	(*PingRes)(nil),                     // 13: urlshortener.PingRes
	(*ShortenBatchURLReq_BatchURL)(nil), // 14: urlshortener.ShortenBatchURLReq.BatchURL
	(*ShortenBatchURLRes_BatchURL)(nil), // 15: urlshortener.ShortenBatchURLRes.BatchURL
	(*GetUsersURLsRes_UserURL)(nil),     // 16: urlshortener.GetUsersURLsRes.UserURL
}
var file_internal_grpc_server_proto_urlshortener_proto_depIdxs = []int32{
	14, // 0: urlshortener.ShortenBatchURLReq.urls:type_name -> urlshortener.ShortenBatchURLReq.BatchURL
	15, // 1: urlshortener.ShortenBatchURLRes.urls:type_name -> urlshortener.ShortenBatchURLRes.BatchURL
	16, // 2: urlshortener.GetUsersURLsRes.urls:type_name -> urlshortener.GetUsersURLsRes.UserURL
	0,  // 3: urlshortener.URLShortener.ShortenURL:input_type -> urlshortener.ShortenURLReq
	2,  // 4: urlshortener.URLShortener.ShortenBatchURL:input_type -> urlshortener.ShortenBatchURLReq
	4,  // 5: urlshortener.URLShortener.GetURL:input_type -> urlshortener.GetURLReq
	6,  // 6: urlshortener.URLShortener.GetUserURLs:input_type -> urlshortener.GetUsersURLsReq
	8,  // 7: urlshortener.URLShortener.DeleteUserURLs:input_type -> urlshortener.DeleteUserURLsReq
	10, // 8: urlshortener.URLShortener.GetStats:input_type -> urlshortener.GetStatsReq
	12, // 9: urlshortener.URLShortener.Ping:input_type -> urlshortener.PingReq
	1,  // 10: urlshortener.URLShortener.ShortenURL:output_type -> urlshortener.ShortenURLRes
	3,  // 11: urlshortener.URLShortener.ShortenBatchURL:output_type -> urlshortener.ShortenBatchURLRes
	5,  // 12: urlshortener.URLShortener.GetURL:output_type -> urlshortener.GetURLRes
	7,  // 13: urlshortener.URLShortener.GetUserURLs:output_type -> urlshortener.GetUsersURLsRes
	9,  // 14: urlshortener.URLShortener.DeleteUserURLs:output_type -> urlshortener.DeleteUserURLsRes
	11, // 15: urlshortener.URLShortener.GetStats:output_type -> urlshortener.GetStatsRes
	13, // 16: urlshortener.URLShortener.Ping:output_type -> urlshortener.PingRes
	10, // [10:17] is the sub-list for method output_type
	3,  // [3:10] is the sub-list for method input_type
	3,  // [3:3] is the sub-list for extension type_name
	3,  // [3:3] is the sub-list for extension extendee
	0,  // [0:3] is the sub-list for field type_name
}

func init() { file_internal_grpc_server_proto_urlshortener_proto_init() }
func file_internal_grpc_server_proto_urlshortener_proto_init() {
	if File_internal_grpc_server_proto_urlshortener_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_internal_grpc_server_proto_urlshortener_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*ShortenURLReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_grpc_server_proto_urlshortener_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*ShortenURLRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_grpc_server_proto_urlshortener_proto_msgTypes[2].Exporter = func(v any, i int) any {
			switch v := v.(*ShortenBatchURLReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_grpc_server_proto_urlshortener_proto_msgTypes[3].Exporter = func(v any, i int) any {
			switch v := v.(*ShortenBatchURLRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_grpc_server_proto_urlshortener_proto_msgTypes[4].Exporter = func(v any, i int) any {
			switch v := v.(*GetURLReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_grpc_server_proto_urlshortener_proto_msgTypes[5].Exporter = func(v any, i int) any {
			switch v := v.(*GetURLRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_grpc_server_proto_urlshortener_proto_msgTypes[6].Exporter = func(v any, i int) any {
			switch v := v.(*GetUsersURLsReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_grpc_server_proto_urlshortener_proto_msgTypes[7].Exporter = func(v any, i int) any {
			switch v := v.(*GetUsersURLsRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_grpc_server_proto_urlshortener_proto_msgTypes[8].Exporter = func(v any, i int) any {
			switch v := v.(*DeleteUserURLsReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_grpc_server_proto_urlshortener_proto_msgTypes[9].Exporter = func(v any, i int) any {
			switch v := v.(*DeleteUserURLsRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_grpc_server_proto_urlshortener_proto_msgTypes[10].Exporter = func(v any, i int) any {
			switch v := v.(*GetStatsReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_grpc_server_proto_urlshortener_proto_msgTypes[11].Exporter = func(v any, i int) any {
			switch v := v.(*GetStatsRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_grpc_server_proto_urlshortener_proto_msgTypes[12].Exporter = func(v any, i int) any {
			switch v := v.(*PingReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_grpc_server_proto_urlshortener_proto_msgTypes[13].Exporter = func(v any, i int) any {
			switch v := v.(*PingRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_grpc_server_proto_urlshortener_proto_msgTypes[14].Exporter = func(v any, i int) any {
			switch v := v.(*ShortenBatchURLReq_BatchURL); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_grpc_server_proto_urlshortener_proto_msgTypes[15].Exporter = func(v any, i int) any {
			switch v := v.(*ShortenBatchURLRes_BatchURL); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_grpc_server_proto_urlshortener_proto_msgTypes[16].Exporter = func(v any, i int) any {
			switch v := v.(*GetUsersURLsRes_UserURL); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_internal_grpc_server_proto_urlshortener_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   17,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_internal_grpc_server_proto_urlshortener_proto_goTypes,
		DependencyIndexes: file_internal_grpc_server_proto_urlshortener_proto_depIdxs,
		MessageInfos:      file_internal_grpc_server_proto_urlshortener_proto_msgTypes,
	}.Build()
	File_internal_grpc_server_proto_urlshortener_proto = out.File
	file_internal_grpc_server_proto_urlshortener_proto_rawDesc = nil
	file_internal_grpc_server_proto_urlshortener_proto_goTypes = nil
	file_internal_grpc_server_proto_urlshortener_proto_depIdxs = nil
}
